# Generated by Django 4.0.4 on 2022-05-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_remove_register_name_register_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name1',
            new_name='name',
        ),
    ]
