# Generated by Django 4.0.4 on 2022-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_rename_name_register_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
