# Generated by Django 4.0.4 on 2022-05-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_alter_dt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
