# Generated by Django 4.0.4 on 2022-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_alter_dt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
